config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"

  # 会員用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    post "/users/sign_out", to: "devise/sessions#destroy"
    post "/users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  scope module: :public do
    resources :recipes, only: [:new, :create, :update, :index, :show, :edit, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "search"
        get "favorite"
      end
    end
    resources :users, only: [:show, :update, :edit, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      collection do
        get "search"
      end
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :recipes, only: [:index, :destroy]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :recipe_image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :serving, presence: true
  validates :recipe_image, attached_file_presence: true

  belongs_to :user
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :category

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #検索用
  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "introduction", "name", "serving", "updated_at", "user_id"]
  end

end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.ingredients
    @steps = @recipe.steps
    @comment = Comment.new
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to admin_recipes_path
  end

end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/views/admin/recipes/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-10 my-3">
    <h2 class="my-3">レシピ一覧</h2>
      <% @recipes.each do |recipe| %>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td><%= image_tag recipe.recipe_image.variant(resize: "150x150^", gravity: "center", crop: "200x200+0+0") %></td>
              <td><%= recipe.name %></td>
              <td>
                <%= link_to "削除", admin_recipe_path(recipe.id), method:  :delete, data: {confirm: "本当に削除しますか？"}, class:  "btn btn-danger" %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>