config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"

  # 会員用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :user do
    post "/users/sign_out", to: "devise/sessions#destroy"
    post "/users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  scope module: :public do
    resources :recipes, only: [:new, :create, :update, :index, :show, :edit, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get "search"
        get "favorite"
      end
    end
    resources :users, only: [:show, :update, :edit, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      collection do
        get "search"
      end
    end
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :recipes, only: [:index, :destroy]
  end
end

app/views/layouts/_header.html.erb
<header class="pc-header">
  <nav class="navbar mr-aut navbar-expand-md" style="background-color: #86AABE;">
    <div class="row w-100 align-items-center mx-5">
      <a class="navbar-brand" href="/">
        <span class=""><%= image_tag("logo.png", :size =>"180x100") %></span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse h-100" id="navbarNavDropdown">
        <ul class="navbar-nav w-100 justify-content-end mx-5">

          <!--管理者側がログインしている時-->
          <% if admin_signed_in? %>
              <li class="nav-item text-right">
                <%= link_to "レシピ一覧", admin_recipes_path, class: "btn btn-outline-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_users_path, class: "btn btn-outline-light ml-3" %>
              </li>
              <li class="nav-item">
                <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-light ml-3" %>
              </li>

            <!--会員側がログインしている時 -->
          <% elsif user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Top", root_path, class: "btn btn-outline-light ml-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-outline-light ml-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "レシピを見る", recipes_path, class: "btn btn-outline-light ml-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-light ml-3" %>
            </li>
            <!--検索フォーム-->
            <li class="nav-item ml-3">
              <%= search_form_for @search, url: search_recipes_path, class: "d-flex" do |f| %>
                <%= f.search_field :name_cont, class: "form-control mr-2", placeholder: "キーワードを入力" %>
                <%= f.submit "検索", class: "btn btn-light" %>
              <% end %>
            </li>


            <!--ログインしていない時 -->
          <% else %>
         　  <li class="nav-item">
              <%= link_to "Top", root_path, class: "btn btn-outline-light ml-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'btn btn-outline-light ml-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "レシピを見る", recipes_path, class: "btn btn-outline-light ml-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-light ml-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-light ml-3" %>
            </li>
          <% end %>
          </ul>
      </div>
    </div>
  </nav>
</header>


<header class="sp-header" >
  <div class="pos-f-t" >
  <div class="collapse" id="navbarToggleExternalContent">
    <div class=" p-4" style="background-color: #86AABE; ">
      <ul class="navbar-nav w-100 justify-content-end mx-5">

              <!--管理者側がログインしている時-->
              <% if admin_signed_in? %>
                  <li class="nav-item text-right">
                    <%= link_to "レシピ一覧", admin_recipes_path, class: "btn btn-outline-light" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "会員一覧", admin_users_path, class: "btn btn-outline-light ml-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-light ml-3" %>
                  </li>

                <!--会員側がログインしている時 -->
              <% elsif user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Top", root_path, class: "btn btn-outline-light ml-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-outline-light ml-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "レシピを見る", recipes_path, class: "btn btn-outline-light ml-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-light ml-3" %>
                </li>
                <!--検索フォーム-->
                <li class="nav-item ml-3">
                  <%= search_form_for @search, url: search_recipes_path, class: "d-flex" do |f| %>
                    <%= f.search_field :name_cont, class: "form-control mr-2", placeholder: "キーワードを入力" %>
                    <%= f.submit "検索", class: "btn btn-light" %>
                  <% end %>
                </li>


                <!--ログインしていない時 -->
              <% else %>
             　  <li class="nav-item">
                  <%= link_to "Top", root_path, class: "btn btn-outline-light ml-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: 'btn btn-outline-light ml-3' %>
                </li>
                <li class="nav-item">
                  <%= link_to "レシピを見る", recipes_path, class: "btn btn-outline-light ml-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-light ml-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-light ml-3" %>
                </li>
              <% end %>
              </ul>
    </div>
  </div>
  <nav class="navbar navbar-dark" style="background-color: #86AABE;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MilkKitchen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= flash[:notice] %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class=row>
          <div class="mx-auto">
            <p>CopyRight © </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>